### ISSUE TITLE
내가 생각중인거.

### ISSUE THREAD

**Issue by ParkMinKyu** [SpoonCode/Don#1]
# 블로그

- 태그를 메뉴로 이용한 블로그

## 기능 리스트 (CRUD)
-  관리자(해당 블로그를 관리하는 운영자)
 - 게시글 관리(CRUD) : `글 생성, 삭제, 수정, 추가, 블라인드 처리,이어지는 글쓰기, 태그연동, RSS출력`
 - 댓글 관리(CRUD) : `댓글 생성, 삭제, 수정, 추가, 블라인드 처리, 태그연동`
 - 태그 관리(CRUD) : `태그 생성, 삭제, 수정, 추가`
 - RSS 관리(CRUD) : `RSS를 등록, 수정, 삭제 한다.`
- 사용자(정보를 얻기위해 블로그를 방문한 사람)
 - 사용자는 가입이 아닌 `SNS & (익명+비밀번호)를 통한 댓글 달기`를 허용한다.
 - 게시글 보기(R) : `작성된 게시글을 볼수 있다.`
 - 댓글 관리 (CRUD) : `게시판에 자신의 댓글을 추가, 수정, 삭제할 수 있다.`
 - SNS 로그인 & 댓글 달기 (facebook, tweet, google+, naver) : `댓글작성을 위해 SNS계정을 이용`할 수 있다.
 - SNS 공유 & 추천(facebook, tweet, google+, naver):`정보 공유를 위해 SNS를 이용`한다.
 - 태그 모아보기(R):`해당 블로그의 태그를 클릭하여 태그가 등록된 글 리스트를 확인` 할 수 있다.
 - 글 검색하기 (R) : `제목 or 내용을 검색한다.`
 - RSS구독 : `관리자가 등록한 RSS를 볼수 있다.`

## 사전 준비작업
- 개발 프레임웍 & DB & 사용 할 기술 선정 & 기능 분배
- 개발 시작전 공통 패키징 작업 & DB설계 & 공통 클래스 설정 & Naming Rule 정하기
- repository 등록 & 분업을 시작할 commit 작업 & tag 작업
- branch & tag & 간단한 git 사용법 숙지(commit, pull, push)
- merge or pull requests 작업 범위 정하기

## 대략 생각중인 이미지
![blog main img](https://raw.githubusercontent.com/ParkMinKyu/branch-test/master/img.png)

**Comment by ParkMinKyu** [comment]
일단은 대충 생각했던거 정리했는데 
이런식으로 문서랑 이력을 남기면서 작업하는게 좋은거 같긴하네 
머리속에 있는걸 정리하는게 생각보다 어렵구만 ㅋㅋ

그럼 내용 보고 의견있으면 comment 남기던가 완전 다른거 하고 싶으면 의견 라벨 달아서 새 issue 만들어서 공유 부탁.

**Comment by woniper** [comment]
아 어떤 주제 할지 많이 생각해봤는데요. 개인적인 생각인데 뭔가 개발 도구 같은걸 만들고 싶어서요. 연동이랄까..
첫 번째로 SpringBoot Actuator 말고 dependency 추가해서 사용할 수 있는 Actuator를 하나 생각해봤고,
두 번째로는 Restful API 문서 자동화 프로젝트를 만들어볼까 생각해봤는데요 iodocs, swagger라는게 이미 존재하긴 한데 swagger를 사용해보긴 했는데 조금 불편한게 있었거든요.
근데 문제는 두 가지 다 구체적으로 생각이 안나서요. @ParkMinKyu 형이 올려준거 하는 것도 좋을거 같아요.
추가 사항을 몇 가지 생각해봤는데
1. 설치형
2. Spring Boot, JPA (개인적인 바램)
3. 테스트 코드 작성

**Comment by nanstrong** [comment]
주제를 고르는 일만 남았군요 블로그도 한번쯤 해보고 싶었고 경원이가 낸 의견중에 Actuator랑 문서자동화도 끌리네요
이걸 의견을 조율해서 우선순위를 정해서 프로젝트를 순차적으로 진행하는 것도 나쁘지 않을꺼 같네요
이거 댓글 기능은 없는거죠?

**Comment by ParkMinKyu** [comment]
@woniper 
@nanstrong 
Actuator가 스프링으로 개발된 어플리케이션 모니터링 해주는 라이브러리야?
첨듣는데 ㅋㅋ 이런거도 괜찮은거 같긴 한데 이건 스프링 완전 뜯어보고 사전에 준비작업이 많이 필요할 것같은데. Actuator가 어떤식으로 모니터링 하는지 한번 사용은 해봐야 할 것같네
대충 훑어봐선 그냥 JSON으로 데이터만 뿌려주는거 같은데, 일단 사용을 해봐야 감이 올꺼같긴 하다.
이건 우선 블로그를 만들때 `Spring boot`에 `Actuator`도 사용하고 `UI로 데이터 눈으로 볼수 있게` 표현 해주는거 추가 하면서 일단 기능한번 써보고, 블로그 `서버API를 REST`로만든 다음에 만든 걸 `문서화 하게끔 연동해도 프로젝트 진행` 해도 될꺼같네. 

## 대충 정리하면

1. 일단 `github`이랑 `git`랑 사용법 숙지 할 겸 `blog 프로젝트를 진행`
2. 개발 관련해서는 나도 `spring-boot`랑 `jpa`쓰는거랑 자기가 개발한 부분에 대해서 `테스트 코드 작성`하는게 좋을꺼 같고, 상대방이 작업한 `소스에 대해서 리뷰`도 해주는것도 좋을꺼 같음. 나도 소스 작성하다보면 중구난방 정신없어져서 ㅋㅋ
3. `front단`은 걍 `Bootstrap`만 사용하면 될꺼같고 `jquery`는 필수고. `Angular`는 생각해봤는데 만들 블로그가 컨셉이 `SPA`로 하긴 좀 아닌거 같아서 제외 솔직히 `Angular로 소비하는 시간이 너무 많을듯.`
4. `DB`는 `sql-lite나 h2`같은 파일DB로 해도 괜찮을꺼같음 설치랑 백업이 간편하니까. yobi도 파일 DB 쓰는거 같았는데. 개발하면서 CRUD말고 DB상의 큰 기능은 딱히 필요할꺼 같진 않음
5. boot로 어플리케이션 만들면서 내장 톰켓, 다 포함해서 배포하면 설치형 블로그 간단히 될꺼 같음.
6. 위에 적은거 말고도 생각나는 기능이 더있긴 한데 초장부터 너무 많이 집어넣고 시작하긴 아닌거 같고 우선 `적힌 기능만이라도 제대로된 v1.0 한번 완성했으면함.`
7. 진행중에 `Actuator`와 `자동 문서화` 관련해서 생각나는 아이디어는 `단순한거라도 이슈`에 등록(의견 Label부착)

그 후 추가 기능은 천천히 다음 프로젝트 진행하면서 시간 있는 사람이 추가 시켜주면 되니까.
아니면 잘되면 사람들 영입해서 팀원들 늘리는것도 괜찮을꺼 같음 

github만 이용해서 공통 플젝을 첨해보니까 하면서 문제점이 생길수 있으니
우선은 우리끼리 플젝하나 제대로 하면서 룰을 정하고 프로젝트 늘리는 방향으로 나가면 좋을듯.
중간에 시간나면 자주는 아니더라도 오프라인으로 만나서 조율도 필요할꺼같고

그럼 보고 추가의견이나 생각나는 사항 있으면 comment 추가해줘:+1:

**Comment by woniper** [comment]
front는 reactjs 사용해도 좋을거 같구요. reactjs는 MVC 프레임웍 아니라 ui 프레임웍이라 사용하기 간단하고 데이터 바인딩하기도 편해요. 깊게 사용은 안해봤고 한번 찾아보시면 금방 이해하실거에요.
DB는 인디비 사용하는거 찬성이고 내장 톰캣 사용하는것도 찬성이에요.
그리고 7번 같은 경우는 이번 프로젝트 어느정도 만들고 나서 고민해도 늦지 않을거 같아요.
아 앞에 말해주셔서 생각난건데 어차피 블로그도 관리자페이지가 있어야되니까 actuator를 관리자 페이지에 넣어도 괜찮을거 같아요. 그래서 다 생각하셨겠지만
어떤거 쓸지 한번 정리해보자면
Spring Boot, Data JPA, Actuator, Test, Security(로그인, sns 연동) 이정도로 사용할거 같네요.

**Comment by ParkMinKyu** [comment]
@woniper 
@nanstrong 
그럼 우선 블로그 진행하는거로 하고
기본적으로 boot에 jpa써서 CRUD 샘플있는거 경원이가 셋팅해서 소스 올려주고

##분업을 어떤식으로 진행하는게 좋을지 생각해봤는데

1. 테이블 단위로 나눠서 각자 해당 테이블에 관련된 기능 개발
 - 게시글테이블, 태그테이블, 댓글테이블, 등등 하나씩 맡아서
2. 기능단위로 나눠서 하고 싶은부분 우선개발
3. 관리자, 공통 & 사용자, front 나눠서 개발
 - 관리자는 관리자 기능만개발
 - 공통은 프레임웍전체적인 셋팅을 맡고 개발중에 다른사람이 DB추가나 공통 기능이 필요하다고하면 공통 맡은사람이 추가해주는 방식으로
 - front는 화면쪽 개발이고

이런식으로 분업해서 하면 될꺼같은데 개인적으론 분업이 확실히 되려면 3번이 최적일꺼같은데
다른 방식 좋은거 있으면 생각해서 알려줘~

**Comment by woniper** [comment]
JPA 사용하려면 테이블 중심으로 개발하는건 좋은 방향은 아닌거 같아요. 그렇게 설계하고 개발하는건 orm하고 맞지 않는거 같고 3번 방향으로 가는게 좋은거 같아요.

**Comment by ParkMinKyu** [comment]
@SpoonCode/owners 
ㅇㅋ 그럼 3번 방식으로 하는거로 하고 
돈일이는 시골간다고 했었나
돈일이 오면 기간이랑 맡고싶은 부분 분업하고 시작하면 되겠다.

**Comment by nanstrong** [comment]
저도 다 찬성~~ 큰틀이 정해졌으니. 주말이나 시간날때 만나서 좀더 세부적으로 이야기 해요~

**Comment by ParkMinKyu** [comment]
[Repository](https://github.com/SpoonCode/SpooBlog)에서 개발 시작
